# Generated by Django 3.0.5 on 2020-09-27 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_materia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Materia',
        ),
    ]
