# Generated by Django 3.0.5 on 2020-09-30 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='view_materias_usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField()),
                ('username', models.CharField(max_length=30)),
                ('materias', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'view_materias_usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='view_notasusuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=30)),
                ('materia_id', models.IntegerField()),
                ('data', models.DateField()),
                ('materia', models.CharField(max_length=30)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nota_minima', models.FloatField(blank=True, null=True)),
                ('nota_maxima', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'view_notasusuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='view_perguntas_materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia_id', models.IntegerField()),
                ('nr_pergunta', models.IntegerField()),
                ('pergunta', models.CharField(blank=True, max_length=1000, null=True)),
                ('nome_materia', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'view_perguntas_materia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='view_provas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30)),
                ('user_id', models.IntegerField()),
                ('materia_id', models.IntegerField()),
                ('nome_materia', models.CharField(max_length=30)),
                ('pergunta_id', models.IntegerField()),
                ('nr_pergunta', models.IntegerField()),
                ('pergunta', models.CharField(blank=True, max_length=1000, null=True)),
                ('resposta', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'view_provas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='view_provas_resumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30)),
                ('materia_id', models.IntegerField()),
                ('nome_materia', models.CharField(max_length=30)),
                ('qtde_perguntas', models.IntegerField()),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'view_provas_resumo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlunoMateriaNota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('materia', models.CharField(blank=True, max_length=30, null=True)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('nota_minima', models.FloatField(blank=True, null=True)),
                ('nota_maxima', models.FloatField(blank=True, null=True)),
                ('img_materia', models.FileField(blank=True, null=True, upload_to='alunos/alunos.images')),
            ],
        ),
        migrations.CreateModel(
            name='Perguntas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia_id', models.IntegerField()),
                ('nr_pergunta', models.IntegerField()),
                ('pergunta', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Respostas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia_id', models.IntegerField()),
                ('pergunta_id', models.IntegerField()),
                ('resposta', models.CharField(blank=True, max_length=1000, null=True)),
                ('usuario', models.CharField(max_length=30)),
                ('status', models.CharField(blank=True, default='Criada', max_length=20, null=True)),
                ('resultado', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlunoMateria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materias', models.CharField(blank=True, max_length=300, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
