# Generated by Django 3.0.5 on 2020-09-30 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respostas',
            name='resultado',
        ),
    ]
