# Generated by Django 3.0.5 on 2020-10-01 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_respostas_resultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='respostas',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
