# Generated by Django 3.0.5 on 2020-10-01 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_respostas_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='perguntas',
            name='peso',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
