# Generated by Django 3.0.5 on 2020-10-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0005_perguntas_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='respostas',
            name='total_peso',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
