# Generated by Django 3.0.5 on 2020-10-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0008_provashistory_respostashistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunomaterianota',
            name='prova_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respostas',
            name='prova_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
