# Generated by Django 3.0.5 on 2020-10-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0009_auto_20201002_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='provashistory',
            name='prova_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respostashistory',
            name='prova_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
