# Generated by Django 3.0.5 on 2020-10-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0010_auto_20201002_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='view_provas_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prova_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('data', models.DateField()),
                ('username', models.CharField(max_length=30)),
                ('materia_id', models.IntegerField()),
                ('nome_materia', models.CharField(max_length=30)),
                ('pergunta_id', models.IntegerField()),
                ('nr_pergunta', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('pergunta', models.CharField(blank=True, max_length=1000, null=True)),
                ('resposta', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(max_length=30)),
                ('nota', models.IntegerField(blank=True, null=True)),
                ('resultado', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'view_provas_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='view_provas_resumo_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prova_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=30)),
                ('materia_id', models.IntegerField()),
                ('nome_materia', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('nota', models.IntegerField(blank=True, null=True)),
                ('total_peso', models.IntegerField(blank=True, null=True)),
                ('qtde_perguntas', models.IntegerField()),
            ],
            options={
                'db_table': 'view_provas_resumo_history',
                'managed': False,
            },
        ),
    ]
