# Generated by Django 3.0.5 on 2020-10-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0011_view_provas_history_view_provas_resumo_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='respostashistory',
            name='pergunta',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
