# Generated by Django 3.0.5 on 2020-09-26 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=30)),
                ('des_categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('img_categoria', models.FileField(blank=True, null=True, upload_to='produtos/produtos.images')),
                ('status_categoria', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa')], default=0, max_length=10)),
                ('idioma', models.CharField(choices=[('pt', 'pt'), ('en', 'en')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=50)),
                ('codigo_produto', models.CharField(blank=True, max_length=10)),
                ('descricao_produto', models.CharField(blank=True, max_length=200, null=True)),
                ('preco_produto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('img_produto', models.FileField(blank=True, upload_to='produtos.images/')),
                ('status_produto', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default=0, max_length=10)),
                ('idioma', models.CharField(choices=[('pt', 'pt'), ('en', 'en')], max_length=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Categoria')),
            ],
        ),
    ]
