from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('homeMaterias/', views.homeMaterias, name="homeMaterias"),
    path('cadastrarMateria/', views.cadastrarMateria, name="cadastrarMateria"),
    path('editarMateria/', views.editarMateria, name="editarMateria"),
    path('alterarMateria/', views.alterarMateria, name="alterarMateria"),
    path('editarMateria/<int:materia_id>/', views.editarMateria, name="editarMateria"),
    path('deleteMateria/<int:materia_id>/', views.deleteMateria, name="deleteMateria"),
    path('salvarAlteracoesMateria/<int:materia_id>/', views.salvarAlteracoesMateria, name="salvarAlteracoesMateria"),
    path('usuariosMaterias/', views.usuariosMaterias, name="usuariosMaterias"),
    path('salvarUsuariosMaterias/', views.salvarUsuariosMaterias, name="salvarUsuariosMaterias"),
    path('listarUsuariosMaterias/', views.listarUsuariosMaterias, name="listarUsuariosMaterias"),
    path('viewNotasUsuarios/', views.viewNotasUsuarios, name="viewNotasUsuarios"),
    path('filtrarNotasUsuarioData/', views.filtrarNotasUsuarioData, name="filtrarNotasUsuarioData"),
    path('filtrarNotasUsuario/', views.filtrarNotasUsuario, name="filtrarNotasUsuario"),
    path('listarMateriasNotas/', views.listarMateriasNotas, name="listarMateriasNotas"),
    path('deleteUsuarioMateria/<slug:username>/', views.deleteUsuarioMateria, name="deleteUsuarioMateria"),
    path('viewMateriasUsuario/<int:materia_id>/', views.viewMateriasUsuario, name="viewMateriasUsuario"),
    path('editarMateriaUsuario/<slug:username>/', views.editarMateriaUsuario, name="editarMateriaUsuario"),
    path('salvarUserMaterias/<slug:username>/', views.salvarUserMaterias, name="salvarUserMaterias"),
    path('viewMateriasUsuario/<int:materia_id>/', views.viewMateriasUsuario, name="viewMateriasUsuario"),
    path('criarPergunta/', views.criarPergunta, name="criarPergunta"),
    path('inserirPergunta/', views.inserirPergunta, name="inserirPergunta"),
    path('listarPerguntasMateria/', views.listarPerguntasMateria, name="listarPerguntasMateria"),
    path('listarPerguntas/', views.listarPerguntas, name="listarPerguntas"),
    path('editarPergunta/<int:pergunta_id>/', views.editarPergunta, name="editarPergunta"),
    path('deletePergunta/<int:materia_id>/<int:pergunta_id>/', views.deletePergunta, name="deletePergunta"),
    path('salvarAlteracoesPergunta/<int:pergunta_id>/', views.salvarAlteracoesPergunta, name="salvarAlteracoesPergunta"),
    path('listarMateriasProva/', views.listarMateriasProva, name="listarMateriasProva"),
    path('listarAlunosMateria/', views.listarAlunosMateria, name="listarAlunosMateria"),
    path('criarProva/', views.criarProva, name="criarProva"),
    path('viewProvasAlunos/', views.viewProvasAlunos, name="viewProvasAlunos"),
    path('deleteProva/<int:materia_id>/<slug:usuario>/', views.deleteProva, name="deleteProva"),
    path('inicioProvaAluno/', views.inicioProvaAluno, name="inicioProvaAluno"),
    path('salvarProva/', views.salvarProva, name="salvarProva"),
    path('listarPerguntasProva/', views.listarPerguntasProva, name="listarPerguntasProva"),
    path('concluirProva/<nome_materia>/', views.concluirProva, name="concluirProva"),
    path('verProvaAluno/<int:materia_id>/<slug:usuario>/', views.verProvaAluno, name="verProvaAluno"),
    path('salvarCorrecoes/', views.salvarCorrecoes, name="salvarCorrecoes"),
    path('salvarNotaUsuario/<data>/<slug:aluno>/<int:prova_id>/', views.salvarNotaUsuario, name="salvarNotaUsuario"),
    path('arquivarProva/<int:materia_id>/<slug:aluno>/', views.arquivarProva, name="arquivarProva"),
    path('viewProvasHistory/', views.viewProvasHistory, name="viewProvasHistory"),
    path('mostrarDetalhesProva/<int:prova_id>/', views.mostrarDetalhesProva, name="mostrarDetalhesProva"),
    path('filtrarMateriaHistory/', views.filtrarMateriaHistory, name="filtrarMateriaHistory"),
    path('filtrarProvaAluno/', views.filtrarProvaAluno, name="filtrarProvaAluno")
]
