# Generated by Django 3.0.5 on 2020-09-24 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('pt', 'pt'), ('en', 'en'), ('es', 'es')], default=0, max_length=10)),
                ('descricao', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
